version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: oj_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: oj_backend
    env_file:
      - ./backend/.env
    environment:
      - TMPDIR=/home/ec2-user/oj-tmp
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ec2-user/oj-tmp:/home/ec2-user/oj-tmp
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: oj_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
